#!/bin/bash
file_name="$(xclip -out -selection clipboard 2> /dev/null)"

files_path=""
if [[ "$file_name" == file:///* ]]
then
    files_path="${file_name:7}"
elif [[ "$file_name" == /* ]]
then
    files_path=$file_name
else
    echo "No file in clipboard"
    exit 1
fi

for file in $files_path
do
    echo "pasting $file"
    cp -r $file .
done
