#!/bin/bash
file_names="$(xclip -out -selection clipboard 2> /dev/null)"

for file_name in $file_names; do
    if [[ "$file_name" == file:///* ]]; then
        file_path="${file_name:7}"
    elif [[ "$file_name" == /* ]]; then
        file_path=$file_name
    else
        echo "No file in clipboard"
        exit 1
    fi

    echo "pasting $file_path"
    cp -r $file_path .
done
